name: chatview
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 1.3.1
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues
repository: https://github.com/SimformSolutionsPvtLtd/flutter_chatview

platforms:
  android:
  ios:

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: '>=3.10.3'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  url_launcher: ^6.3.0
  emoji_picker_flutter: ^3.1.0
  any_link_preview: ^3.0.2
  image_picker: ^1.1.2
  audio_waveforms: ^1.0.5
  # For formatting time locale in message receipts
  timeago: ^3.7.0
  cached_network_image: ^3.4.0
  linkify_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:

